### ISSUE TITLE
Offer to join org and help maintain this

### ISSUE THREAD

**Issue by alerque** [vim-awesome/vim-awesome#390] opened 2020-01-08 07:15 UTC
This project is an awesome idea and started out well, but it has fallen into disrepair and the current state of affairs is a mess. It looks like it's been a few years since it got any real attention, and it needs both some love on the code side of things and a lot of database culling. For example I notice there are 4 entries for a plugin I maintain, only one of which even has the right links. There are reams and reams of links that are not even vim plugins!

I am the instigator of @preservim, and currently an active maintainer of plugins such as [nerdcommenter](https://github.com/preservim/nerdcommenter), [tagbar](https://github.com/majutsushi/tagbar), @vim-pandoc & friends, [vim-pencil](https://github.com/reedes/vim-pencil) & friends, [vim-ledger](https://github.com/ledger/vim-ledger), [vim-sile](https://github.com/sile-typesetter/vim-sile), [vim-tridactyl](https://github.com/tridactyl/vim-tridactyl), and others.

I would like to offer to help. I would propose being added to the org as an owner, be given whatever access is necessary to deploy the code from the repository to the domain, and get access to the active DB and any management tools there is for it.

My goals would be to:

* Get the database cleaned up of cruft that is detracting from it being useful. Non vim-plugins, duplicates, etc.
* Encourage the community here to actually contribute by being responsive to PRs, encouraging issue reporters to pitch in with fixes, and generally making sure that when people contribute work (such as the issue reports about bad entries) they actually get taken care of.
* Gradually improving the UI, submission process, etc. so it stays cleaner in the future.

**Comment by alerque** [comment] 2020-01-08 07:23
Just in case repository notifications are turned off, pinging @divad12 and @captbaritone directly as they are publicly listed on the org... there may be more relevant people but Github doesn't make it possible to see who all actually has repo ownership.

**Comment by captbaritone** [comment] 2020-01-08 17:58
This seems reasonable to me. The most I’ve had time/motivation to do in the last few years is restart the server when it occasionally crashes.

@sophiebits pays the bills on the server that it runs on, so I’ll defer to her on access to the server.

Probably the best place to start would be to take a look at the code and try to understand where the duplicate entries are coming from, or why they are not getting correctly deduped.

Of our many failure, the most critical ones I’m aware of are:

* Failures to correctly dedupe plugins
* False positives in our code which tries to determine what is actually a plugin.
* A lack of human effort to respond to human submissions.

Surely there are others too, but those are the ones which I’m most aware of.

**Comment by divad12** [comment] 2020-01-27 10:27
@alerque let me know if you need any directions on this. I'm the responsible party for the buggy deduping code 😝

I wrote this a while ago on the architecture: https://github.com/vim-awesome/vim-awesome/raw/master/docs/report.pdf (Section 5.3 contains relevant details on deduping. Recommend start reading on page 20, section 5)

I'm supportive of your proposal to help! It should be possible to create a local version of the database through the setup instructions from the README, and replicate errors from the production DB from there (and via cron scripts in the repo too).

😄

**Comment by alerque** [comment] 2020-01-27 10:39
@divad12 Thanks for the offer, I might take you up on that if/when I start digging in. Right now I'm kind of waiting to see if I actually get access to stuff before I put a bunch of work into PR's that are just going to sit around forever like current issues have ;-)

**Comment by divad12** [comment] 2020-01-27 14:45
> @divad12 Thanks for the offer, I might take you up on that if/when I start digging in. Right now I'm kind of waiting to see if I actually get access to stuff before I put a bunch of work into PR's that are just going to sit around forever like current issues have ;-)

What would you like access to first, and what specifically would you do first with the access to that?

**Comment by divad12** [comment] 2020-05-07 23:53
Someone using my key?

> Hi @divad12,
> 
> On May 6th, 2020 at 07:13 (UTC) your personal access token (For VimAwesome scraping locally on my laptop) using python-requests/2.9.1 was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/user/443562/repos
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team
> 
>

**Comment by alerque** [comment] 2020-05-08 12:10
Negative from my side. If you didn't do so I would revoke the token, it must have leaked somewhere.

**Comment by HP4k1h5** [comment] 2020-05-10 10:29
> A lack of human effort to respond to human submissions.

hi, im happy to help triage new submissions or setup a support ticket triage system through github or whatever is preferred.

**Comment by alerque** [comment] 2020-05-11 06:01
@HP4k1h5 Thanks for the offer. Unfortunately at this point to date nothing has really come of this attempt to revive the project. We haven't heard back from the admin of the current infrastructure about getting access to deploy anything that does get worked on and I still don't have any access to actually work on this repo. Given that old contributions have sat around for years without attention I'm kind of unwilling to sink a bunch of time into working on a fork until it's clear there will be a path to get any improvements deployed. If and when that happens I'll ping you again.

**Comment by divad12** [comment] 2020-05-12 02:33
@alerque what sort of access do you need — I'm wondering if a dump of the production DB would be useful?

**Comment by kristijanhusak** [comment] 2020-07-27 13:17
I'd like to help on this also.

**Comment by divad12** [comment] 2020-07-28 05:43
> I'd like to help on this also.

Great! How can we help you get started?

**Comment by kristijanhusak** [comment] 2020-07-28 06:02
@divad12 access to reviewing submitted plugins and ability to add them myself would be a good start.
For technical part, I can assist @alerque , since i'm not a python developer.

**Comment by divad12** [comment] 2020-08-03 04:12
@kristijanhusak awesome. Send an email to emacs@vimawesome.com and I'll send you a database dump where you can start reviewing plugins.

**Comment by kristijanhusak** [comment] 2020-08-03 10:45
@divad12 what an email :D

Isn't there a way to do reviewing directly on vimawesome.com? Or this is just a precaution from your side?

**Comment by alerque** [comment] 2020-08-03 11:02
@divad12 A dump of the production database is a start, but what we really need is access to production! This project has been lots of people offering to help going back to many PRs that never got reviewed and accepted but if there is no path to actually get our contributions into production what's the point? I am still interested in helping out with this and can coordinate and effort to cleanup and fixup the current site, but I can't do it without actually access to this repo and the production db. I don't want to sink a bunch of time working on it unless it's clear it will go somewhere.

**Comment by divad12** [comment] 2020-08-04 03:27
@kristijanhusak unfortunately there is no way to do direct reviewing on vimawesome.com. It would be nice to build such a feature!

@alerque I hear your desire to help and to have access to production to be able to help, and see that, even after 8 months, you are still eager to. I'll email you with next steps.

**Comment by kristijanhusak** [comment] 2020-08-04 06:02
@divad12 i'll definitely try to introduce this first. It's pain to do reviewing like this.
Can you also add me as collaborator here and allow me to merge PRs into master? Direct push to master should be forbidden anyway.

**Comment by divad12** [comment] 2020-08-05 05:20
@kristijanhusak Submit a PR and I'll add you as collaborator if it looks good and gets merged. :)

**Comment by divad12** [comment] 2020-08-11 04:11
> @divad12 access to reviewing submitted plugins and ability to add them myself would be a good start.
> For technical part, I can assist @alerque , since i'm not a python developer.

And with #391 you are now a Python developer, @kristijanhusak 🤣

**Comment by kristijanhusak** [comment] 2020-09-13 07:29
@alerque I can create you a user for vimawesome so you can approve submitted plugins. Give me your email and i'll send you credentials.

**Comment by TornaxO7** [comment] 2021-04-26 19:58
What's the current status? Is vimawesome gonna be revived now? https://www.reddit.com/r/neovim/comments/mydhln/i_wanna_create_a_dead_simple_and_free_website_for/ neovim started a discussion about it.

**Comment by kristijanhusak** [comment] 2021-04-26 20:46
@TornaxO7 i don't think that should be the case. Codebase is very outdated (Python 2, old react version). It's maybe better to have something rewritten from scratch and have data migrated from here to there.

**Comment by TornaxO7** [comment] 2021-04-26 20:48
Hm... that's sad to here... vimawesome was such a nice platform to find plugins :( So shouldn't that be announced on the website/README?

**Comment by kristijanhusak** [comment] 2021-04-26 20:52
It's not up to me. I'm just a contributor, not an author.
Since I introduced login and review feature, i check once a month and confirm few submitted plugins, but I don't have time to go through all of them. If you want to help, I can make you a user so you can login and review some of the submitted plugins yourself.

**Comment by TornaxO7** [comment] 2021-04-26 20:54
And what's with cleaning up the database and remove non-vim-plugins?

**Comment by TornaxO7** [comment] 2021-04-26 20:56
I don't know how much I can help, but I'd like to give it a try, so yeah, you can create an account for me :)

**Comment by kristijanhusak** [comment] 2021-04-27 13:44
@TornaxO7 if you can please contact me via Twitter DM (https://twitter.com/kristijan_husak) so we can set you up an account.

**Comment by TornaxO7** [comment] 2021-04-27 13:56
oof... eh I don't have a twitter account.... could you write me an email instead? (tornax07@gmail.com)

**Comment by TornaxO7** [comment] 2021-04-27 21:56
https://www.reddit.com/r/neovim/comments/mydhln/i_wanna_create_a_dead_simple_and_free_website_for/
There has been a discussion about creating a vim-awesome-like platform. It might be worth it to interact with the maintainer, since the project is pretty new so changes can be made "easily".

**Comment by TornaxO7** [comment] 2021-05-16 08:33
Ok, to refresh the status of this issue, there's a "new" plugin-platform now: https://nvim-awesome.vercel.app/

I started [a little issue](https://github.com/lucax88x/nvim-awesome/issues/29) wondering if we could "port" the plugins from vim-awesome to nvim-awesome, since the project is pretty new.

**Comment by cbartlett** [comment] 2022-07-20 18:38
I'm taking up the cause of maintenance on this and cleaning up old issues. Thanks for your concern!

**Closed by cbartlett** 2022-07-20 18:38 UTC

**Comment by sophiebits** [comment] 2022-07-20 18:42
Thank you @cbartlett!!
