### ISSUE TITLE
bash-support is failing

### ISSUE THREAD

**Issue by Fashaun** [vim-awesome/vim-awesome#347] opened 2017-05-16 07:20 UTC
Hi ,

the bash-support install guide is fail when you use vim-plug

**Comment by captbaritone** [comment] 2017-05-16 13:49
Any idea what's going wrong? Any error messages/screenshots you could share?

**Comment by captbaritone** [comment] 2017-05-17 03:01
Closing as a dupe of #348.

**Closed by captbaritone** 2017-05-17 03:01 UTC

**Comment by captbaritone** [comment] 2017-05-17 03:12
This should be resolved. Could you confirm that it now works for you? http://vimawesome.com/plugin/bash-support-vim
